sudo: required
language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'

before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mup

- openssl aes-256-cbc -K $encrypted_328fda7e6827_key -iv $encrypted_328fda7e6827_iv
  -in secrets.tar.enc -out secrets.tar -d  # Decrypt secrets.tar.enc
- tar xvf secrets.tar # Decompress secrets.tar
services: mongodb

script:
- iron --test --settings ../config/development/settings.json --release velocity:METEOR@1.2.0.1_1
after_success:
- iron deploy testCIByMike.meteor.com
# - mup deploy
#- curl -L http://git.io/vqbln | sh
